name: Build Modrinth Modpack

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pack
        run: |
          mkdir -p pack/
          cp modrinth.index.json pack/
          cd pack/
          zip -r ../carrots.mrpack .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: carrots
          path: carrots.mrpack
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: carrots.mrpack
          tag_name: ${{ github.ref_name }}
